services:
  bbikkibbikki:
    image: oht2050/bbikkibbikki:latest
    ports:
      - "80:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      PROD_DB_URL: ${PROD_DB_URL}
      PROD_DB_USERNAME: ${PROD_DB_USERNAME}
      PROD_DB_PASSWORD: ${PROD_DB_PASSWORD}
      PROD_REDIS_HOST: ${PROD_REDIS_HOST}
      PROD_REDIS_PORT: ${PROD_REDIS_PORT}
      PROD_JWT_SECRET_KEY: ${PROD_JWT_SECRET_KEY}
      PROD_S3_BUCKET_NAME: ${PROD_S3_BUCKET_NAME}
      PROD_SQS_NAME: ${PROD_SQS_NAME}
      PROD_S3_ACCESS_KEY: ${PROD_S3_ACCESS_KEY}
      PROD_S3_SECRET_KEY: ${PROD_S3_SECRET_KEY}


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8.0  # 또는 다른 버전 선택 가능
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PROD_DB_PASSWORD}  # 원하는 root 비밀번호 설정
      MYSQL_DATABASE: baseball  # 생성할 기본 데이터베이스 이름
    ports:
      - "3306:3306"  # MySQL 기본 포트