services:
  bbikkibbikki-api:
    image: oht2050/bbikkibbikki-api:latest
    ports:
      - "80:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      PROD_DB_HOST: ${PROD_DB_HOST}
      PROD_DB_NAME: ${PROD_DB_NAME}
      PROD_DB_USERNAME: ${PROD_DB_USERNAME}
      PROD_DB_PASSWORD: ${PROD_DB_PASSWORD}
      PROD_REDIS_HOST: ${PROD_REDIS_HOST}
      PROD_REDIS_PORT: ${PROD_REDIS_PORT}
      PROD_JWT_SECRET_KEY: ${PROD_JWT_SECRET_KEY}
      PROD_S3_BUCKET_NAME: ${PROD_S3_BUCKET_NAME}
      PROD_SQS_NAME: ${PROD_SQS_NAME}
      PROD_AWS_ACCESS_KEY: ${PROD_AWS_ACCESS_KEY}
      PROD_AWS_SECRET_KEY: ${PROD_AWS_SECRET_KEY}

  bbikkibbikki-chat:
    image: oht2050/bbikkibbikki-chat:latest
    ports:
      - "81:8081"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      PROD_DB_HOST: ${PROD_DB_HOST}
      PROD_DB_NAME: ${PROD_DB_NAME}
      PROD_DB_USERNAME: ${PROD_DB_USERNAME}
      PROD_DB_PASSWORD: ${PROD_DB_PASSWORD}
      PROD_REDIS_HOST: ${PROD_REDIS_HOST}
      PROD_REDIS_PORT: ${PROD_REDIS_PORT}
      PROD_JWT_SECRET_KEY: ${PROD_JWT_SECRET_KEY}
      PROD_S3_BUCKET_NAME: ${PROD_S3_BUCKET_NAME}
      PROD_SQS_NAME: ${PROD_SQS_NAME}
      PROD_AWS_ACCESS_KEY: ${PROD_S3_ACCESS_KEY}
      PROD_AWS_SECRET_KEY: ${PROD_S3_SECRET_KEY}