services:
  local-mysql:
    image: mysql
    container_name: bbikibbiki-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./config/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    platform: linux/arm64

  local-redis:
    image: redis
    container_name: bbikibbiki-redis
    ports:
      - "6379:6379"
    platform: linux/arm64