version: '3'
services:
  bbikkibbikki:
    image: oht2050/bbikkibbikki:latest
    ports:
      - "80:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      SQS_NAME: ${SQS_NAME}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"