spring:
  datasource:
    url: jdbc:mysql://localhost:3306/baseball
    username: ${db.username:1234}
    password: ${db.password:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  secret:
    key: ${jwt.key:1234}

cloud:
  aws:
    s3:
      bucket: ${S3_NAME:1234}
    stack.auto: false
    region.static: ap-northeast-2
    sqs:
      queue-name:
        queue: ${SQS_NAME:1234}
    credentials:
      accessKey: ${S3_ACCESS:1234}
      secretKey: ${S3_SECRET:1234}