spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  secret:
    key: ${PROD_JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: ${PROD_S3_BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    cloudfront:
      domain: ${PROD_CLOUD_FRONT}
    sqs:
      queue-name:
        queue: ${PROD_SQS_NAME}
    credentials:
      accessKey: ${PROD_AWS_ACCESS_KEY}
      secretKey: ${PROD_AWS_SECRET_KEY}