name: Deploy to EC2

on:
  push:
    branches:
      - cicd-oht

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHub에서 소스 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4


      # EC2에 SSH로 연결하여 Docker 이미지 Pull 및 실행
      - name: Deploy Docker Image to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          port: 22
          script: |
            # Docker 서비스 시작
            sudo systemctl start docker

            # 기존 컨테이너 중지 및 삭제
            docker stop bbikkibbikki || true
            docker rm bbikkibbikki || true

            # 최신 Docker 이미지 Pull
            docker pull oht2050/bbikkibbikki:latest

            # 새로운 컨테이너 실행
            docker run -d -p 8080:8080 --name bbikkibbikki -e PROD_DB_URL=${{secrets.PROD_DB_URL}} -e PROD_DB_USERNAME=${{secrets.PROD_DB_USERNAME}} -e PROD_DB_PASSWORD=${{secrets.PROD_DB_PASSWORD}} -e PROD_REDIS_HOST=${{secrets.PROD_REDIS_HOST}} -e PROD_REDIS_PORT=${{secrets.PROD_REDIS_PORT}} -e PROD_JWT_SECRET_KEY=${{secrets.PROD_JWT_SECRET_KEY}} -e PROD_S3_BUCKET_NAME=${{secrets.PROD_S3_BUCKET_NAME}} -e PROD_SQS_NAME=${{secrets.PROD_SQS_NAME}} -e PROD_S3_ACCESS_KEY=${{secrets.PROD_S3_ACCESS_KEY}} -e PROD_S3_SECRET_KEY=${{secrets.PROD_S3_SECRET_KEY}} oht2050/bbikkibbikki:latest