name: Deploy to EC2

on:
  push:
    branches:
      - cicd-oht

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # GitHub에서 소스 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.S3_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.S3_SECRET_KEY }}
          application_name: bbikkibbikki
          environment_name: Bbikkibbikki-env-2
          version_label: ${{ github.sha }}  # 동적으로 GitHub SHA를 version label로 설정
          region: ap-northeast-2
          deployment_package: deploy.zip
